### ISSUE TITLE
Bug with Held Item Tooltips

### ISSUE THREAD

**Issue by QuImUfu** [digitalshadowhawk/PopEnchantTagsRevived#1]
in the moment you enchant tags are overlapping with the Held Item Tooltips when in survivalmode.
see: http://imgur.com/a/GyB6n
Maybe you should move you mods tag upwards when in survivalmode.

**Comment by digitalshadowhawk** [comment]
Fixed for both survival and adventure modes in version 1.1.1
Hadn't ever noticed that the held item tooltips actually moved based on game mode until now

I'm mostly wondering why you have Depth Strider on a sword now.....
